<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="refer_by_instance_class" nsURI="..." nsPrefix="sdf">
  <eClassifiers xsi:type="ecore:EClass" name="C">
    <eTypeParameters name="T">
      <eBounds eClassifier="//Reader"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="w" eType="//Writer" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="X" instanceClassName="java.io.Reader"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Y" instanceClassName="java.io.Writer"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Reader" instanceClassName="java.io.Reader"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Writer" instanceClassName="java.io.Writer"/>
</ecore:EPackage>
